### ISSUE TITLE
use with node.js websocket?

### ISSUE THREAD

**Issue by rpedela** [jprante/elasticsearch-transport-websocket#2]
I am trying to simply connect right now, but it is not working due to ES returning status code 200 instead of 101. It very easily could be that I am using the wrong URL, port, etc. I am not even sure how to debug this, so any pointers would be helpful.

Install

```
npm install websocket
```

Code

``` js
var WebSocketClient = require('websocket').client;

var ws = new WebSocketClient();
ws.connect('ws://localhost:9400/_stats');
ws.on('connect', function(connection) {
    console.log('connected!');
});
ws.on('connectFailed', function(err) {
    console.log('ERROR: ' + err);
});
```

Output

```
ERROR: Server responded with a non-101 status: 200
Response Headers Follow:
content-type: application/json; charset=UTF-8
content-length: 97
```

**Comment by gaving** [comment]
@rpedela Hey, I don't suppose you are aware of any changes which would have broken your node example? 

Trying myself and while I can connect and send messages, I can't seem to receive anything back.

Elasticsearch 1.4.2 / latest build of transport-websocket

**Comment by rpedela** [comment]
No, I do not. I have switched to using the official ES Node client. Sorry.

**Comment by gaving** [comment]
Ah, no worries. Are you now just polling with the official client?

Basically trying to get some subscription/push going on but until https://github.com/elasticsearch/elasticsearch/issues/1242 is sorted it looks like I'm running out of options!
