### ISSUE TITLE
No artifacts for elasticsearch 1.3.x

### ISSUE THREAD

**Issue by pavlo-yuriychuk** [jprante/elasticsearch-transport-websocket#7]
It is mentioned in your readme that 1.3.x version is supported but, in fact, there are no artifacts for it in this location http://xbib.org/repository/org/xbib/elasticsearch/plugin/elasticsearch-transport-websocket/1.3.1.0/

**Comment by jprante** [comment]
I wiped the plugin repo by accident, sorry. The 1.3.1.0 version is now restored.
